config/routes.rb
EuromenPaintings::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  get 'invoices' => 'invoices#all_invoices'

  get 'estimates' => 'estimates#all_estimates'

  resources :customers do
    resources :estimates
    resources :invoices
  end

  root 'customers#index'
end

app/models/estimate.rb
class Estimate < ActiveRecord::Base
  has_one :invoice
  belongs_to :customers

  after_initialize :set_defaults

  validates_presence_of :estimate_type, :estimate_address, :estimate_city, :estimate_province, :estimate_details, :estimate_amount,
                        :estimate_gst, :estimate_total, :estimated_on_date

  def set_defaults
    self.estimate_city ||= 'Edmonton'
    self.estimate_province ||= 'AB'
  end
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_estimate, only: [:show, :edit, :update, :destroy]

  def index
    @estimates = Estimate.all.where(customer_id: params[:customer_id])
  end

  def all_estimates
    @all_estimates = Estimate.all
  end

  def show
  end

  def new
    @estimate = Estimate.new
  end

  def edit
  end

  def create
    @estimate = Estimate.new(estimate_params)

    @estimate.customer_id = params[:customer_id]
    @estimate.invoice_id = params[:invoice_id]
    @estimate.estimate_desc_id = Date.today.strftime("%y%m%d").to_s << params[:id].to_s

    respond_to do |format|
      if @estimate.save
            binding.pry
        format.html { redirect_to "/customers/#{@estimate.customer_id}/estimates/#{@estimate.id}", notice: 'Estimate was successfully created.'}
        format.json { render action: 'show', status: :created, location: @estimate }
      else
        format.html { render action: 'new' }
        format.json { render json: @estimate.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @estimate.update(estimate_params)
        format.html { redirect_to "/customers/#{@estimate.customer_id}/estimates/#{@estimate.id}", notice: 'Estimate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @estimate.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @estimate.destroy
    respond_to do |format|
      format.html { redirect_to "/customers/#{@estimate.customer_id}", notice: 'Estimate has been removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estimate
      @estimate = Estimate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estimate_params
      params.require(:estimate).permit(:estimate_desc_id, :customer_id, :invoice_id, :estimate_type, :estimate_address, :estimate_city, :estimate_province,
                                      :estimate_city, :estimate_details, :estimated_on_date)
    end
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/views/estimates/_customer_details.html.erb
<div><b><%=customer_full_name(params[:customer_id]) %></b></div>
<div><%=customer_address(params[:customer_id]) %></div>
<div><%=customer_city_postal_code(params[:customer_id]) %></div>
<div><%= customer_phones(params[:customer_id]) %></div>

app/views/estimates/_edit.html.erb
<%= semantic_form_for @estimate, :url => customer_estimate_path do |f| %>
  <%= f.semantic_errors %>
  <%= f.inputs do %>
    <%= f.input :estimate_type, :as => :select, :collection => ["Interior","Exterior","Exterior & Interior"], :label => "Painting type" %>
    <%= f.input :estimate_address %>
    <%= f.input :estimate_city %>
    <%= f.input :estimate_province, :input_html=>{:class=>"datepicker"} %>
    <p class="ckeditor-label">Estimate Detailssssssss</p>
    <%= f.input :estimate_details,:as=>"text", :label => false, :input_html=>{:class=>"ckeditor"} %>
    <%= f.input :estimated_on_date, :input_html=>{:class=>"datepicker"} %>
  <% end %>
  <%= f.actions do %>
    <%= f.action :submit, label: 'Save Changes' %>
  <% end %>
<% end %>


<script type="text/javascript">
$(document).ready(function(){
    $('.datepicker').datepicker();
  })




CKEDITOR.replace( 'estimate_estimate_details',
  {
    toolbar :
    [
      { name: 'basicstyles', items :  ['Format','Font','FontSize','-','Bold','Italic','Underline','-','Undo','Redo','-','Cut','Copy','Paste','-','Outdent','Indent' ] },
      { name: 'paragraph', items : [ 'NumberedList','BulletedList','-','JustifyLeft','JustifyCenter','JustifyRight' ] }
    ]
  });
</script>

app/views/estimates/_form.html.erb
<%= semantic_form_for @estimate, url: customer_estimates_path do |f| %>
  <%= f.semantic_errors %>
  <%= f.inputs do %>
    <%= f.input :estimate_type, as: :select, :collection => ["Interior","Exterior","Exterior & Interior"], :label => "Painting type" %>
    <%= f.input :estimate_address %>
    <%= f.input :estimate_city %>
    <%= f.input :estimate_province %>
    <p class="ckeditor-label">Estimate Details</p>
    <%= f.input :estimate_details, label: false, input_html: {class: "ckeditor"} %>
	<%= f.input :estimate_amount, as: :string, label: 'Amount' %>
	<%= f.input :estimate_gst_include, label: 'Include GST' %>
    <%= f.input :estimate_gst, as: :string, input_html: {readonly: true}, label: 'GST ( 5.00 % )' %>
    <%= f.input :estimate_total, as: :string, input_html: {readonly: true}, label: 'Total' %>
    <%= f.input :estimated_on_date %>
  <% end %>
  <%= f.actions do %>
    <%= f.action :submit, label: 'Save Estimate' %>
  <% end %>
<% end %>

<script>

$(document).ready(function(){
  $('#estimate_estimate_amount').blur(function(){
	  if(isNaN($('#estimate_estimate_amount').val())){
	    alert('Enter the proper estimate amount');
	  }else{
	  	//calculate GST amount and total amount
	  	if($('#estimate_estimate_gst_include').is(':checked')){
		  	var gst = $('#estimate_estimate_amount').val() * 0.05
		  	var gst_rounded = gst.toFixed(2)
	  	}else{
			var gst_rounded = 0
	  	}
	  	var total = parseFloat($('#estimate_estimate_amount').val()) + parseFloat(gst_rounded)
	  	var total_rounded = total.toFixed(2)
		$('#estimate_estimate_gst').val(gst_rounded)
	  	$('#estimate_estimate_total').val(total_rounded)
	  }
  });
});




CKEDITOR.replace( 'estimate_estimate_details',
  {
    toolbar :
    [
      { name: 'basicstyles', items :  ['Format','Font','FontSize','-','Bold','Italic','Underline','-','Undo','Redo','-','Cut','Copy','Paste','-','Outdent','Indent' ] },
      { name: 'paragraph', items : [ 'NumberedList','BulletedList','-','JustifyLeft','JustifyCenter','JustifyRight' ] }
    ]
  });
</script>

app/views/estimates/all_estimates.html.erb
<div class="container-fluid">
  <h4>All Estimates</h4>
   <fieldset>
     <div class="row-fluid">
       <div class="span12">
         <table class="table table-striped">
           <tr class="main-header">
             <th>Estimate #</th>
             <th>Estimate Details</th>
             <th>Created on</th>
			 <th>Customer</th>
             <th style="width: 120px;">&nbsp;</th>
           </tr>
           <% @all_estimates.each do |estimate| %>
           <tr class= "<%= estimate.invoice_id ? 'green-row' : '' %>">
             <td><%= estimate.estimate_desc_id %></td>
             <td><%= estimate.estimate_details.html_safe %></td>
             <td><%= estimate.estimated_on_date.strftime('%B %d, %Y') %></td>
			 <td><%= customer_full_name(estimate.customer_id)%></td>
             <td>
               <div class="btn-group">
                 <%= link_to 'Show Estimate', customer_estimate_path(estimate.customer_id,estimate), class: 'btn btn-mini' %>
                 <%= link_to 'Show Customer', customer_path(estimate.customer_id), class: 'btn btn-mini' %>
                 <% if estimate.invoice_id %>
                    <%= link_to 'Show Invoice', customer_invoices_path(estimate.invoice_id), class: 'btn btn-mini' %>
                  <% else %>
                    <%= link_to 'Create Invoice', new_customer_invoice_path(:estimate_id => estimate.id, :customer_id => estimate.customer_id), class: 'btn btn-mini' %>
                  <% end %>
               </div>
             </td>
           </tr>
         <% end %>
         </table>
       </div>
     </div>

   </fieldset>
   <div style="padding-bottom:10px;">
	   <%= link_to 'Back', customers_path, class: 'btn' %>
   </div>
 </div>

app/views/estimates/edit.html.erb
<h4>Editing estimate</h4>
<div style="margin-left:260px;"><%= render partial: "estimates/customer_details", locals: {customer_id: @estimate.customer_id} %></div>
<%= render 'edit' %>

<td><%= link_to 'Show', customer_estimate_path(@estimate.customer_id,@estimate), class: 'btn btn-mini' %></td>
<td><%= link_to 'Back', customer_estimate_path(@estimate.customer_id,@estimate), class: 'btn btn-mini' %></td>

app/views/estimates/index.html.erb
<div class="container-fluid">
  <h4>All Estimates for <%= customer_full_name(params[:customer_id])%></h4>
   <fieldset>
     <div class="row-fluid">
       <div class="span12">
         <table class="table table-striped">
           <tr class="main-header">
              <th>Estimate #</th>
              <th>Estimate Details</th>
              <th>Created on</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          <% @estimates.each do |estimate| %>
            <tr>
               <td><%= estimate.estimate_desc_id %></td>
               <td><%= estimate.estimate_details.html_safe %></td>
               <td><%= estimate.estimated_on_date.strftime('%B %d, %Y') %></td>
              <td>
                <div class="btn-group">
                 <%= link_to 'Show Estimate', customer_estimate_path(estimate.customer_id,estimate), class: 'btn btn-mini' %>
                 <% unless estimate.invoice_id.blank? %>
                    <%= link_to 'Show Invoice', customer_invoice_path(estimate.customer_id,estimate.invoice_id), class: 'btn btn-mini' %>
                  <% else %>
                    <%= link_to 'Create Invoice', new_customer_invoice_path(:estimate_id => estimate.id, :customer_id => estimate.customer_id), class: 'btn btn-mini' %>
                  <% end %>
                </div>
               </td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </fieldset>
  <div style="padding-bottom:10px;">
      <%= link_to 'Back', customers_path, class: 'btn' %>
      <%= link_to 'New Estimate', new_customer_estimate_path, class: 'btn' %>
	  <br/><br/>
  </div>
</div>

app/views/estimates/new.html.erb
<h4>New estimate</h4>
<div style="margin-left:260px;"><%= render partial: "estimates/customer_details", locals: {customer_id: @estimate.customer_id} %></div>
<%= render 'form' %>

<%= link_to 'Back', customer_estimates_path, class: 'btn btn-mini' %>

app/views/estimates/show.html.erb
<h4>Estimate</h4>
<div style="margin-left:260px;"><%= render partial: "estimates/customer_details", locals: {customer_id: @estimate.customer_id} %></div>

<dl class="dl-horizontal">
  <dt>Estimate Type:</dt>
  <dd><%= @estimate.estimate_type %></dd>
  <dt>Address</dt>
  <dd><%= @estimate.estimate_address %></dd>
  <dt>City:</dt>
  <dd><%= @estimate.estimate_city %></dd>
  <dt>Province:</dt>
  <dd><%=@estimate.estimate_province %></dd>
  <dt>Details:</dt>
  <dd><%= @estimate.estimate_details.html_safe %></dd>
  <dt>Estimated on:</dt>
  <dd><%= @estimate.estimated_on_date.strftime('%B %d, %Y') %></dd>
</dl>
<br/>
<div class="btn-group">
  <%= link_to 'Edit', edit_customer_estimate_path(@estimate.customer_id,@estimate), class: 'btn btn-mini' %>
  <%= link_to 'Back', customer_estimate_path(@estimate.customer_id,@estimate), class: 'btn btn-mini' %>
</div>