config/routes.rb
EuromenPaintings::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  get 'invoices' => 'invoices#all_invoices'

  get 'estimates' => 'estimates#all_estimates'

  resources :customers do
    resources :estimates
    resources :invoices
  end

  root 'customers#index'
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  has_one :estimate
  belongs_to :customers

  validates_presence_of :invoice_details, :invoice_created_on, :invoice_amount, :invoice_gst, :invoice_total

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  def index
    @invoices = Invoice.all.where(customer_id: params[:customer_id])
  end

  def all_invoices
    @all_invoices = Invoice.all
  end

  def show
  end

  def new
    @invoice = Invoice.new
  end

  def edit
  end

  def create
    @invoice = Invoice.new(invoice_params)
    @invoice.customer_id = params[:customer_id]

    respond_to do |format|
      if @invoice.save
        update_estimate(@invoice) if @invoice.estimate_id
        format.html { redirect_to "/customers/#{@invoice.customer_id}/invoices/#{@invoice.id}", notice: 'Invoice was successfully created.' }
        format.json { render action: 'show', status: :created, location: @invoice }
      else
        format.html { render action: 'new' }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to "/customers/#{@invoice.customer_id}/invoices/#{@invoice.id}", notice: 'Invoice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to"/customers/#{@invoice.customer_id}", notice: 'Invoice has been removed.'  }
      format.json { head :no_content }
    end
  end

  private

    def update_estimate(invoice)
      estimate = Estimate.find(invoice.estimate_id)
      estimate.update_column(:invoice_id, invoice.id)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:invoice_desc_id, :po_number, :invoice_details, :invoice_created_on, :customer_id, :estimate_id)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_edit.html.erb
<%= semantic_form_for @invoice, :url => customer_invoice_path do |f| %>
  <%= f.semantic_errors %>
  <%= f.inputs do %>
  	<%= f.input :estimate_id, :as => "hidden", :value => params[:estimate_id]  %>
    <%= f.input :invoice_desc_id, :label => "Description" %>
    <%= f.input :po_number, :label => "PO Number" %>
    <p class="ckeditor-label">Details</p>
    <%= f.input :invoice_details, :as=>"text", :label => false, :input_html=>{:class=>"ckeditor"} %>
    <%= f.input :invoice_created_on, :label => "Date Created" %>
  <% end %>
  <%= f.actions do %>
    <%= f.action :submit, label: 'Submit' %>
  <% end %>
<% end %>

<script>
CKEDITOR.replace( 'invoice_details',
  {
    toolbar :
    [
      { name: 'basicstyles', items :  ['Format','Font','FontSize','-','Bold','Italic','Underline','-','Undo','Redo','-','Cut','Copy','Paste','-','Outdent','Indent' ] },
      { name: 'paragraph', items : [ 'NumberedList','BulletedList','-','JustifyLeft','JustifyCenter','JustifyRight' ] }
    ]
  });
</script>

app/views/invoices/_form.html.erb
<!-- display customer info -->

<%= semantic_form_for @invoice, :url => customer_invoices_path do |f| %>

  <%= f.semantic_errors %>
  <%= f.inputs do %>

  	<%= f.input :estimate_id, :as => "hidden", :value => params[:estimate_id]  %>
    <%= f.input :invoice_desc_id, :label => "Description" %>
    <%= f.input :po_number, :label => "PO Number" %>
    <p class="ckeditor-label">Details</p>
    <%= f.input :invoice_details, :as=>"text", :label => false, :input_html=>{:class=>"ckeditor"} %>
    <%= f.input :invoice_created_on, :label => "Date Created" %>
  <% end %>
  <%= f.actions do %>
    <%= f.action :submit, label: 'Submit' %>
  <% end %>
<% end %>


<script>
CKEDITOR.replace( 'invoice_invoice_details',
  {
    toolbar :
    [
      { name: 'basicstyles', items :  ['Format','Font','FontSize','-','Bold','Italic','Underline','-','Undo','Redo','-','Cut','Copy','Paste','-','Outdent','Indent' ] },
      { name: 'paragraph', items : [ 'NumberedList','BulletedList','-','JustifyLeft','JustifyCenter','JustifyRight' ] }
    ]
  });
</script>

app/views/invoices/all_invoices.html.erb
<div class="container-fluid">
  <h4>All Invoices</h4>
   <fieldset>
     <div class="row-fluid">
       <div class="span12">
         <table class="table table-striped">
           <tr class="main-header">
              <th>Description</th>
              <th>PO number</th>
              <th>Details</th>
              <th>Created on</th>
			  <th>Customer</th>
              <th style="width: 120px;">&nbsp;</th>
            </tr>

          <% @all_invoices.each do |invoice| %>
            <tr>
              <td><%= invoice.invoice_desc_id %></td>
              <td><%= invoice.po_number %></td>
              <td><%= invoice.invoice_details.html_safe %></td>
              <td><%= invoice.invoice_created_on.strftime('%B %d, %Y') %></td>
			  <td><%= customer_full_name(invoice.customer_id)%></td>
              <td>
                <div class="btn-group">
                 <%= link_to 'Show Invoice', customer_invoice_path(invoice.customer_id,invoice), class: 'btn btn-mini' %>
                 <%= link_to 'Show Customer', customer_path(invoice.customer_id), class: 'btn btn-mini' %>
                 <% unless invoice.estimate_id.blank? %>
                    <%= link_to 'Show Estimate', customer_estimate_path(invoice.customer_id,invoice.estimate_id), class: 'btn btn-mini' %>
                  <% else %>
                    <%= link_to 'Create Estimate', new_customer_estimate_path(invoice), class: 'btn btn-mini' %>
                  <% end %>
               </div>
               </td>
            </tr>
          <% end %>
        </table>
       </div>
      </div>
  </fieldset>
  <div style="padding-bottom:10px;">
	 	<%= link_to 'Back', customers_path, class: 'btn' %>
  </div>
</div>

app/views/invoices/edit.html.erb
<h4>Editing invoice</h4>
<div style="margin-left:260px;"><%= render partial: "estimates/customer_details", locals: {customer_id: @invoice.customer_id} %></div>
<%= render 'edit' %>

<td><%= link_to 'Show', customer_invoice_path(@invoice.customer_id,@invoice), class: 'btn btn-mini' %></td>
<td><%= link_to 'Back', customer_invoice_path(@invoice.customer_id,@invoice), class: 'btn btn-mini' %></td>

app/views/invoices/index.html.erb
<div class="container-fluid">
  <h4>All Invoices for <%= customer_full_name(params[:customer_id])%></h4>
   <fieldset>
     <div class="row-fluid">
       <div class="span12">
         <table class="table table-striped">
           <tr class="main-header">
              <th>Invoice #</th>
			  <th>PO Number</th>
              <th>Invoice Details</th>
              <th>Created on</th>
              <th></th>
              <th></th>
            </tr>
          <% @invoices.each do |invoice| %>
            <tr>
		        <td><%= invoice.invoice_desc_id %></td>
		        <td><%= invoice.po_number %></td>
		        <td><%= invoice.invoice_details.html_safe %></td>
		        <td><%= invoice.invoice_created_on.strftime('%B %d, %Y') %></td>
              <td>
                <div class="btn-group">
                 <%= link_to 'Show Invoice', customer_invoice_path(invoice.customer_id,invoice), class: 'btn btn-mini' %>
                 <% if invoice.estimate_id %>
                    <%= link_to 'Show Estimate', customer_estimate_path(invoice.customer_id,invoice.estimate_id), class: 'btn btn-mini' %>
				 <% else %>
				 	<div class='btn btn-mini disabled'>No Estimate</div>
				 <% end %>
                </div>
               </td>
            </tr>

          <% end %>
        </table>
      </div>
    </div>
    <%= link_to 'Back', customers_path, class: 'btn' %>
    <%= link_to 'New Invoice', new_customer_invoice_path, class: 'btn' %>
  </fieldset>
</div>

app/views/invoices/new.html.erb
<h4>New invoice</h4>

<div style="margin-left:260px;"><%= render partial: "estimates/customer_details", locals: {customer_id: @invoice.customer_id} %></div>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>
<h4>Invoice</h4>
<div style="margin-left:260px;"><%= render partial: "estimates/customer_details", locals: {customer_id: @invoice.customer_id} %></div>

<dl class="dl-horizontal">
	<dt>Invoice desc:</dt>
	<dd><%= @invoice.invoice_desc_id %></dd>
	<dt>PO number:</dt>
	<dd><%= @invoice.po_number %></dd>
	<dt>Details:</dt>
	<dd><%= @invoice.invoice_details.html_safe %></dd>
	<dt>Created on:</dt>
	<dd><%= @invoice.invoice_created_on.strftime('%B %d, %Y') %></dd>
</dl>
<br/>
<div class="btn-group">
	<td><%= link_to 'Edit', edit_customer_invoice_path(@invoice.customer_id,@invoice), class: 'btn btn-mini' %></td>
	<td><%= link_to 'Back', customer_invoice_path(@invoice.customer_id,@invoice), class: 'btn btn-mini' %></td>
</div>