config/routes.rb
EuromenPaintings::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  get 'invoices' => 'invoices#all_invoices'

  get 'estimates' => 'estimates#all_estimates'

  resources :customers do
    resources :estimates
    resources :invoices
  end

  root 'customers#index'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :estimates
  has_many :invocies

  after_initialize :set_defaults

  validates_presence_of :first_name, :last_name, :address, :city, :province, :postal_code, :home_phone

  def set_defaults
    self.city ||= 'Edmonton'
    self.province ||= 'AB'
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
    @customers = Customer.all
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def edit
  end

  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @customer }
      else
        format.html { render action: 'new' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :address, :city, :province, :postal_code, :home_phone, :cell_phone, :comments)
    end
end

app/helpers/customer_helper.rb
module CustomerHelper
  def customer_full_name(id)
    customer = Customer.find(id)
    return customer.first_name.capitalize + ' ' + customer.last_name.capitalize if customer
  end
  def customer_address(id)
    customer = Customer.find(id)
    return customer.address if customer
  end
  def customer_city_postal_code(id)
    customer = Customer.find(id)
    return customer.city.capitalize + ', ' + customer.province.capitalize + ' ' + format_postal_code(customer.postal_code) if customer
  end
  def customer_phones(id)
    customer = Customer.find(id)
    return format_phone_number(customer.home_phone) + ', ' + format_phone_number(customer.cell_phone) if customer
  end

  def format_phone_number(number)
    return "(#{number[0..2]}) #{number[3..5]}-#{number[6..-1]}"
  end
  def format_postal_code(number)
    return "#{number[0..2]} #{number[3..5]}"
  end
end

app/views/customers/_form.html.erb
<%= semantic_form_for @customer do |f| %>
  <%= f.semantic_errors %>
  <%= f.inputs do %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :address %>
    <%= f.input :city %>
    <%= f.input :province %>
    <%= f.input :postal_code %>
    <%= f.input :home_phone %>
    <%= f.input :cell_phone %>
    <%= f.input :comments, input_html: {:row => "10"}%>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, label: 'Submit' %>
  <% end %>
<% end %>

app/views/customers/edit.html.erb
<h4>Editing customer</h4>
<hr/>
<%= render 'form' %>

<div class="btn-group">
  <%= link_to 'Show', @customer, class: 'btn btn-mini' %>
  <%= link_to 'Back', customers_path, class: 'btn btn-mini' %>
</div>

app/views/customers/index.html.erb
<div class="container-fluid">
  <h4>All Customers</h4>
   <fieldset>
     <div class="row-fluid">
       <div class="span12">
         <table class="table table-striped">
           <tr class="main-header">
             <th>First Name</th>
             <th>Last Name</th>
             <th>Address</th>
             <th style="width: 120px;">&nbsp;</th>
           </tr>
           <% @customers.each do |customer| %>
           <tr>
             <td><%= customer.first_name %></td>
             <td><%= customer.last_name %></td>
             <td><%= customer.address %></td>
             <td>
               <div class="btn-group">
                 <%= link_to 'Show', customer, class: 'btn btn-mini' %>
                 <%= link_to 'All Estimates', customer_estimates_path(customer), class: 'btn btn-mini' %>
                 <%= link_to 'All Invoices', customer_invoices_path(customer), class: 'btn btn-mini' %>
               </div>
             </td>
           </tr>
         <% end %>
         </table>
       </div>
     </div>
     <%= link_to 'New Customer', new_customer_path, class: 'btn' %>
   </fieldset>
 </div>

app/views/customers/new.html.erb
<h4>New customer</h4>
<hr/>

<%= render 'form' %>

<div class="btn-group">
    <%= link_to 'Back', customers_path, class: 'btn btn-mini' %>
</div>

app/views/customers/show.html.erb
<h4>Customer</h4>
<hr/>

<dl class="dl-horizontal">
  <dt>First Name:</dt>
  <dd><%= @customer.first_name %></dd>
  <dt>Last Name:</dt>
  <dd><%= @customer.last_name %></dd>
  <dt>Address</dt>
  <dd><%= @customer.address %></dd>
  <dt>City:</dt>
  <dd><%= @customer.city %></dd>
  <dt>Province:</dt>
  <dd><%=@customer.province %></dd>
  <dt>Postal Code:</dt>
  <dd><%=@customer.postal_code %></dd>
  <dt>Home Phone:</dt>
  <dd><%= @customer.home_phone %></dd>
  <dt>Cell Phone:</dt>
  <dd><%= @customer.cell_phone %></dd>
  <dt>Comments:</dt>
  <dd><%= @customer.comments %></dd>
</dl>
<br/>
<div class="btn-group">
  <div class="btn-group">
     <%= link_to 'Edit', edit_customer_path(@customer), class: 'btn btn-mini' %>
     <%= link_to 'Back', customers_path, class: 'btn btn-mini' %>
  </div>
</div>