config/routes.rb
EuromenPaintings::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  get 'invoices' => 'invoices#all_invoices'

  get 'estimates' => 'estimates#all_estimates'

  resources :customers do
    resources :estimates
    resources :invoices
  end

  root 'customers#index'
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <div class="header-img">
         <%= link_to image_tag("emp-banner-image-l.jpg"), root_path %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- link_to "Home", root_path, :class => 'brand' % -->
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to('Customers', customers_path) %>
    </li>
    <li>
    <%= link_to('Estimates', estimates_path) %>
    </li>
    <li>
    <%= link_to('Invoices', invoices_path) %>
    </li>
    <li class="pull-right">
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
    </li>
  <% else %>
    <li class="pull-right">
    <%= link_to('Login', new_user_session_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Euro - men Painting Ltd." %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Euro - men Painting Ltd." %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
	<div style="margin-top:150px;">
    <header class="navbar navbar-fixed-top">
      <div style="border:10px solid white;"><%= image_tag("address.jpg") %><%= link_to image_tag("emp-banner-image-l.jpg"), root_path %></div>
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
	</div>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
</html>